services:
   exercise_server:
      container_name: exercise_server
      image: ghcr.io/tobycheese/exercise_server:squashed
      build: .
      ports:
         - 127.0.0.1:8888:8888
      volumes:
         - ./notebooks/:/notebooks
         #- /etc/timezone:/etc/timezone:ro
         #- /etc/localtime:/etc/localtime:ro
