services:
  objectstore:
    container_name: objectstore 
    image: minio/minio
    command: server --address "0.0.0.0:9000" /data
    hostname: objectstore
    expose:
      - "9000"
    environment:
      - MINIO_ROOT_USER=${minioadmin}
      - MINIO_ROOT_PASSWORD=${9zhsG2Vqazhd}
    volumes:
      - ../s3_data:/data
    networks:
      - development
      - production
